openapi: "3.0.0"
info:
  title: File Upload API
  version: "1.0.0"
paths:
   /upload:
     post:
       summary: Uploads a file.
       consumes:
         - multipart/form-data
       parameters:
         - in: formData
           name: upfile
           type: file
           description: The file to upload.

