services:

  postgres:
    container_name: postgres
    image: postgres:14.13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5432:5432"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8085:8080
    command:
      [
        "php",
        "-d",
        "post_max_size=500M",
        "-d",
        "upload_max_filesize=500M",
        "-S",
        "0.0.0.0:8080",
        "-t",
        "/var/www/html",
      ]
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
  ai-server:
    container_name: ai-server
    restart: always
    ports:
      - "8090:8082"
    build:
      context: ./ai-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./ai-server:/app/ai-server
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS=${S3_SECRET_ACCESS}
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - NODE_ENV=${NODE_ENV}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
volumes:
  postgres_data:
